# Generated by Django 5.1 on 2025-10-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atraccione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atraccione',
            name='altura_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='atraccione',
            name='capacidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='atraccione',
            name='estado',
            field=models.CharField(default='Operativa', max_length=50),
        ),
        migrations.AlterField(
            model_name='atraccione',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
    ]
